# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sift < Formula
  desc "A task prioritization tool"
  homepage "https://github.com/mybuddymichael/sift"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.1/sift_0.1.1_macOS_intel.tar.gz"
    sha256 "9ddad6238e4ae83cc6a69b7e849e84e165c0bf27dbde3aec4721d637b8cdc0e2"

    def install
      bin.install "sift"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.1/sift_0.1.1_macOS_apple_silicon.tar.gz"
    sha256 "05cb9a3ab41c2f736c987a9fb05ad15eda56a24b0a3a9206afac76791bf10e73"

    def install
      bin.install "sift"
    end
  end
end
