# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sift < Formula
  desc "A task prioritization tool"
  homepage "https://github.com/mybuddymichael/sift"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.1/sift_0.1.1_macOS_intel.tar.gz"
    sha256 "31b2a01d5ab03672c9739321b325c4fe78d562b38558b878c3e7e3407f48379a"

    def install
      bin.install "sift"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.1/sift_0.1.1_macOS_apple_silicon.tar.gz"
    sha256 "08c0bf4309fed09aa863919a2eb1fed27e7dd9d45454eff8bc13c26e87987c2d"

    def install
      bin.install "sift"
    end
  end
end
