# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SiftThings < Formula
  desc "A task prioritization tool"
  homepage "https://github.com/mybuddymichael/sift"
  version "0.1.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.4/sift_0.1.4_macOS_intel.tar.gz"
    sha256 "716af8ca8315e58a6848aee0255ccda80041915f6b8adc3059ddb4f81018c116"

    def install
      bin.install "sift"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.4/sift_0.1.4_macOS_apple_silicon.tar.gz"
    sha256 "772cb876540ecb2ef4f8ba4d9cbec9abbd6f515b4fe448891369d42d9ce1dc03"

    def install
      bin.install "sift"
    end
  end
end
