# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sift < Formula
  desc "A task prioritization tool"
  homepage "https://github.com/mybuddymichael/sift"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.2/sift_0.1.2_macOS_intel.tar.gz"
    sha256 "31fc698d8de3da2a93ad18b4a29ea0b01134bc4f066efeef13f950f4a4d049c5"

    def install
      bin.install "sift"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.1.2/sift_0.1.2_macOS_apple_silicon.tar.gz"
    sha256 "97b98193278b465befc112efcebbbcb87130519b87b3a4853f740e3df13ddc26"

    def install
      bin.install "sift"
    end
  end
end
