# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SiftThings < Formula
  desc "A task prioritization tool"
  homepage "https://github.com/mybuddymichael/sift"
  version "0.0.1-test"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.0.1-test/sift_0.0.1-test_macOS_intel.tar.gz"
    sha256 "3d28ebe7a02c779367a7ae4daf448a1b6404c6309a09239e962eccb313dbbd75"

    def install
      bin.install "sift"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mybuddymichael/sift/releases/download/v0.0.1-test/sift_0.0.1-test_macOS_apple_silicon.tar.gz"
    sha256 "636c8d0666d85ab8eb5148669d4c2db6b8597fa43d70788d042a4345960c1016"

    def install
      bin.install "sift"
    end
  end
end
